exports.COMMANDS = {
    "La agarra Messi.": "Indica el comienzo del código.",
    "¡gol!": "Indica el final del código.",
    "Va Messi,": "Asigna un valor a la posición actual de la lista. Es el único comando que además necesita que se le pase un parámetro. Es una oración que permite determinar el valor que se asignará.",
    "Encara Messi.": "Asigna un cero a la posición actual de la lista.",
    "Ankara Messi.": "Asigna un cero a la posición actual de la lista.",
    "La mueve Messi por la derecha.": "Cambia la posición a la derecha.",
    "La mueve Messi por la izquierda.": "Cambia la posición a la izquierda.",
    "Juega Messi.": "Muestra por pantalla el número de la posición actual de la lista.",
    "La pisa Messi.": "Muestra por pantalla el caracter correspondiente en UNICODE al número de la posición actual de la lista.",
    "Siempre Messi.": "Toma un input numérico del usuario, y lo guarda en la posición actual de la lista. Si el input no es un número entero, se ignora.",
    "Gambetea Messi.": "Toma un input del usuario, y guarda el número correspondiente en UNICODE al primer caracter que se ingresa.",
    "Sigue Messi.": "Si la posición actual es cero, se saltea todos los comandos hasta encontrarse un 'vuelve Messi'. Si no lo es, ejecuta los comandos hasta encontrarse con un comando 'vuelve Messi' y luego vuelve al comando. Una vez que vuelve, corrobora de vuelta el valor de la posición actual, y actúa de la misma forma.",
    "Vuelve Messi.": "Indica el final de un bucle de comandos iniciado por un comando 'sigue Messi'.",
    "Corre Messi.": "Copia el contenido de la posición actual de la lista al portapapeles.",
    "Amaga Messi.": "Copia el contenido del portapapeles a la posición actual de la lista."
}

exports.NOUNS = [
    "actuación", "actuaciones",
    "astro", "astros",
    "banda", "bandas",
    "calidad", "calidades",
    "campo", "campos",
    "cancha", "canchas",
    "centro", "centros",
    "clase", "clases",
    "dios", "dioses",
    "estadio", "estadios",
    "estrella", "estrellas",
    "figura", "figuras",
    "galaxia", "galaxias",
    "gambeta", "gambetas",
    "habilidad", "habilidades",
    "ídola", "ídolo", "ídolos", "ídolos",
    "jugada", "jugadas",
    "jugador", "jugadora", "jugadores", "jugadoras",
    "lateral", "laterales",
    "leo", "lio", "leonel", "lionel",
    "muchacho", "muchachos", "muchacha", "muchachas",
    "mundo", "mundos",
    "país", "países",
    "partido", "partidos",
    "pelota", "pelotas",
    "pibe", "pibes", "piba", "pibas",
    "planeta", "planetas",
    "potencial", "potenciales",
    "pulga", "pulgas",
    "república", "repúblicas",
    "talento", "talentos",
    "titán", "titanes",
    "tribuna", "tribunas",
    "toda", "todo", "todas", "todos",
]

exports.ADJECTIVES = [
    "argentina", "argentino", "argentinas", "argentinos",
    "favorita", "favorito", "favoritas", "favoritos",
    "fenomenal", "fenomenales",
    "futbolística", "futbolísticas", "futbolístico", "futbolísticos",
    "habilidosa", "habilidoso", "habilidosas", "habilidosos",
    "increible", "increibles",
    "irrepetible", "irrepetibles",
    "impecable", "impecables",
    "impresionante", "impresionantes",
    "magistral", "magistrales",
    "maravilloso", "maravillosa", "maravillosos", "maravillosas",
    "mundial", "mundiales",
    "nacional", "nacionales",
    "talentosa", "talentoso", "talentosas", "talentosos",
    "titánica", "titánico", "titánicas", "titánicos",
    "tremenda", "tremendo", "tremendas", "tremendos",
    "única", "único", "únicas", "únicos",
]
